import * as dotenv from "dotenv";
dotenv.config();

import OpenAI from 'openai'
import { IpMetadata } from "@story-protocol/core-sdk";
import { client, account } from './utils'
import { uploadJSONToIPFS } from "./utils/uploadToIpfs";
import { createHash } from "crypto";
import { Address } from "viem";
import { zeroAddress } from 'viem'

async function main() {
  //Generate Image 
  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  })

  const image = await openai.images.generate({ 
    model: 'dall-e-2', 
    prompt: 'A cute baby sea otter' 
  });

  console.log(image.data[0].url) // the url to the newly created image 
}

//Set IP Metadata

const ipMetadata: IpMetadata = client.ipAsset.generateIpMetadata({
    title: 'Dall-E 2 Image',
    description: 'An image generated by Dall-E 2',
    ipType: 'image',
    attributes: [
      {
        key: 'Model',
        value: 'dall-e-2',
      },
      {
        key: 'Prompt',
        value: 'A White cat ',
      },
    ],
    creators: [
      {
        name: '0xGareeb',
        contributionPercent: 100,
        address: account.address,
      },
    ],
  }) 
}

//Set up your NFT Metadata

const nftMetadata = {
    name: 'Image Ownership NFT',
    description: 'This NFT represents ownership of the image generated by Dall-E 2',
    image: image.data[0].url,
    attributes: [
      {
        key: 'Model',
        value: 'dall-e-2',
      },
      {
        key: 'Prompt',
        value: 'A cute baby sea otter',
      },
    ],
  } 
}

//upload your metadata


 const ipIpfsHash = await uploadJSONToIPFS(ipMetadata);
  const ipHash = createHash("sha256")
    .update(JSON.stringify(ipMetadata))
    .digest("hex");
  const nftIpfsHash = await uploadJSONToIPFS(nftMetadata);
  const nftHash = createHash("sha256")
    .update(JSON.stringify(nftMetadata))
    .digest("hex");
}

//Register the NFT as an IP Asset

const response = await client.ipAsset.mintAndRegisterIpAssetWithPilTerms({
    spgNftContract: process.env.SPG_NFT_CONTRACT_ADDRESS as Address,
    terms: [], // IP already has non-commercial social remixing terms. You can add more here.
    ipMetadata: {
      ipMetadataURI: `https://ipfs.io/ipfs/${ipIpfsHash}`,
      ipMetadataHash: `0x${ipHash}`,
      nftMetadataURI: `https://ipfs.io/ipfs/${nftIpfsHash}`,
      nftMetadataHash: `0x${nftHash}`,
    },
    txOptions: { waitForTransaction: true },
  });

  console.log(
    `Root IPA created at transaction hash ${response.txHash}, IPA ID: ${response.ipId}`
  );
  console.log(
    `View on the explorer: https://explorer.story.foundation/ipa/${response.ipId}`
  ); 
}

main();

